app:
    jwtExpirationInMs: 604800000
    jwtSecret: JWTSuperSecretKey
katharsis:
    pathPrefix: /api
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    port: 8080
spring:
    datasource:
        password: ''
        tomcat:
            max-active: 50
            max-idle: 20
            max-wait: 20000
            min-idle: 15
        url: jdbc:mysql://localhost:3306/tt_db
        username: root
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                enable_lazy_load_no_trans: true
                format_sql: true
                id:
                    new_generator_mappings: false
